### ISSUE TITLE
Unable to start plugin

### ISSUE THREAD

**Issue by Shaun-Fong** [remiheens/mattermost-docker-arm#32]
"Unable to activate plugin","caller":"app/plugin.go:171","plugin_id":"focalboard","bundle_path":"/mattermost/plugins/focalboard","error":"unable to start plugin: focalboard: unable to generate plugin checksum: read /mattermost/plugins/focalboard: is a directory"}

looks like a folder permission issue, Idk how to fix it😭

**Comment by remiheens** [comment]
Hi, 

Can you post the output of this command ’ ls -la /mattermost/plugins/’ ?

**Comment by Shaun-Fong** [comment]
I have already given up XD

**Comment by remiheens** [comment]
Ok fine, what have you doing to fix this ? Perhaps, I can create a documentation section about it.

Le 3 janv. 2024, 04:02, à 04:02, Shaun Fong ***@***.***> a écrit:
