### ISSUE TITLE
Update to 9.4.1

### ISSUE THREAD

**Issue by MartinKuhl** [remiheens/mattermost-docker-arm#35]
Hi @remiheens 

I tried to update from 9.3 to 9.4.1 as a result I found the follow issues in the DB logs:
`2024-01-24 09:19:01.290 UTC [113] ERROR:  there is no unique or exclusion constraint matching the ON CONFLICT specification
2024-01-24 09:19:01.290 UTC [113] STATEMENT:  INSERT INTO Systems (Name,Value) VALUES ($1,$2) ON CONFLICT (name) DO UPDATE SET Value = $3`

and in the application the following:

`fatal app/migrations.go:647 > timestamp=2024-01-24 10:20:56.459 +01:00 msg=(app.App).DoPermissionsMigrations failed error=doPermissionsMigration: We encountered an error saving the system property., failed to upsert system property: pq: there is no unique or exclusion constraint matching the ON CONFLICT specification
`

**Comment by remiheens** [comment]
Hi Martin, 

What is your database server ? postgres ? mysql ?
Did you try to run migration directly in cli ?

**Comment by MartinKuhl** [comment]
Hi @remiheens I am using your rheens/mattermost-db image. I just updated the version in the docker-compose file. 
I thought that a migration between 9.3 and 9.4 wasn't required. 
What is the best way, in your opinion to run the migration and what command should I use?

**Comment by MartinKuhl** [comment]
as I see v9.3 of your docker db-image is using PG_VERSION=16.1 and also the 9.4 is using this version. There shouldn't be a requirement for a migration isn't it?

**Comment by MartinKuhl** [comment]
I can Update the db up to 9.5.1 but as soon as I update the app to a more recent version than 9.3.0 the above mentioned errors are shown in the logs.

**Comment by MartinKuhl** [comment]
clean installation fixed the issue
