### ISSUE TITLE
new version and new repo structure

### ISSUE THREAD

**Issue by MartinKuhl** [remiheens/mattermost-docker-arm#5]
They moved the web-app & mmctl repo to a new monorepo under https://github.com/mattermost/mattermost-server
So the build process have to be adjusted and version 8 was now released ;-) .

**Comment by remiheens** [comment]
Yes, I'm working on it ... See  https://github.com/remiheens/mattermost-docker-arm/pull/6

**Comment by MartinKuhl** [comment]
Do you are going to update your Docker hub repo as well? https://hub.docker.com/u/rheens

**Comment by remiheens** [comment]
Yes, but i've not enough time tonight for debugging.

I will create 8.1.2 docker release for the ESR version and the latest major release 9.0.0



Le 20 sept. 2023, 12:49, à 12:49, "Martin K." ***@***.***> a écrit:

**Comment by remiheens** [comment]
@MartinKuhl I've released docker image v8.1.2.

I've upgraded my raspi from v7.10.0 to v8.1.2

**Comment by MartinKuhl** [comment]
@remiheens thanks a lot, now I am on version v.8.1.2 too ;-)

**Comment by MartinKuhl** [comment]
any plans for v9?

**Comment by remiheens** [comment]
Currently working on it, you can see branch.

Le 23 sept. 2023, 09:15, à 09:15, "Martin K." ***@***.***> a écrit:

**Comment by remiheens** [comment]
@MartinKuhl just to inform you that I release v9.0.0 docker image ;)

**Comment by MartinKuhl** [comment]
Thanks a lot, I had to migrate the v15 database to v16 but now it is working again
